### ISSUE TITLE
Doesnt Work under openSUSE Tumbleweed KDE

### ISSUE THREAD

**Issue by DoctorCr4nk** [MatthiasSchinzel/sysmon#5] opened 2020-10-08 15:01 UTC
I tried the README.md Instructions to install your tool, but it didn't work.

```
bash: cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20201005"
```

Tested Python 2.7.18:
```
bash: python2 sysmon.py 
Traceback (most recent call last):
  File "sysmon.py", line 1, in <module>
    from PyQt5 import QtWidgets, uic
ImportError: No module named PyQt5
```
 and Python 3.8.5:
```
bash: python3 sysmon.py 
/bin/sh: iwconfig: command not found
Traceback (most recent call last):
  File "sysmon.py", line 593, in <module>
    main()
  File "sysmon.py", line 587, in main
    main = MainWindow()
  File "sysmon.py", line 101, in __init__
    self.s = sysinfo()
  File "/home/$USER/GitExtern/sysmon/src/gather_data.py", line 59, in __init__
    self.get_max_connection_speed()
  File "/home/$USER/GitExtern/sysmon/src/gather_data.py", line 263, in get_max_connection_speed
    self.max_connection_speed.append(processes[-1].split()[1]
IndexError: list index out of range
```
PIP Output:
```
bash: pip install pyqtgraph pyqt5
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyqtgraph in /usr/local/lib/python3.8/site-packages (0.11.0)
Requirement already satisfied: pyqt5 in /usr/local/lib64/python3.8/site-packages (5.15.1)
Requirement already satisfied: numpy>=1.8.0 in /usr/local/lib64/python3.8/site-packages (from pyqtgraph) (1.19.2)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /usr/local/lib64/python3.8/site-packages (from pyqt5) (12.8.1)
```

**Comment by rany2** [comment] 2020-10-08 15:04
Use `bash -c 'PATH=$PATH:/sbin python3 ./sysmon.py'` instead.

**Comment by rany2** [comment] 2020-10-08 15:06
A possible fix for this is for `sysmon.py` to automatically add `/sbin` to it's `PATH`.

**Comment by MatthiasSchinzel** [comment] 2020-10-08 15:21
Thank you both so much for the comments. 

@DoctorCr4nk Your pip is installing for python 3. If you want to use python 2 use pip2 install pyqtgraph pyqt5

@analotia Thank you so much for solving this issue. I couldn't have done it without you!

**Comment by MatthiasSchinzel** [comment] 2020-10-08 15:28
@DoctorCr4nk please try again!

**Comment by MatthiasSchinzel** [comment] 2020-10-10 12:11
Lets merge these two issues

Duplicate of iwconfig: command not found #4

**Closed as completed** 2020-10-11 10:55 UTC
